import hashlib
import json
from datetime import datetime
from flask import request
from app.infrastructure.database.models.models import (
    db, PlatformIdentityConfig, CompanyInformationConfig, CompanyContactsConfig,
    CompanyAddressesConfig, BrandingAssetsConfig, DocumentTemplateConfig,
    SettingUsageMap, Organization
)

class DocumentBrandingService:
    """Centralized Document Identity, Branding & Template Management Engine."""

    _cache = {}

    @classmethod
    def invalidate_cache(cls):
        """Invalidate in-memory branding cache so changes immediately take effect across all generators."""
        cls._cache.clear()

    @classmethod
    def load(cls, org_id=None):
        """Unified entry point for loading branding context."""
        return cls.get_branding_context(org_id)

    @classmethod
    def get_branding_context(cls, org_id=None):
        """Fetch unified branding configuration with hierarchical fallback (Org Override -> Global Default)."""
        cache_key = f"context:{org_id}"
        if cache_key in cls._cache:
            return cls._cache[cache_key]

        # Fetch Global Defaults
        platform = PlatformIdentityConfig.query.filter_by(org_id=None).first()
        company = CompanyInformationConfig.query.filter_by(org_id=None).first()
        contacts = CompanyContactsConfig.query.filter_by(org_id=None).first()
        addresses = CompanyAddressesConfig.query.filter_by(org_id=None).first()
        assets = BrandingAssetsConfig.query.filter_by(org_id=None).first()

        # If org_id provided, check for custom org identity overrides
        org_obj = None
        if org_id:
            org_obj = db.session.get(Organization, org_id)
            org_plat = PlatformIdentityConfig.query.filter_by(org_id=org_id).first()
            org_comp = CompanyInformationConfig.query.filter_by(org_id=org_id).first()
            org_cont = CompanyContactsConfig.query.filter_by(org_id=org_id).first()
            org_addr = CompanyAddressesConfig.query.filter_by(org_id=org_id).first()
            org_assets = BrandingAssetsConfig.query.filter_by(org_id=org_id).first()

            if org_plat: platform = org_plat
            if org_comp: company = org_comp
            if org_cont: contacts = org_cont
            if org_addr: addresses = org_addr
            if org_assets: assets = org_assets

        org_name = (company.legal_company_name if company and company.legal_company_name else (company.trading_name if company and company.trading_name else (org_obj.name if org_obj else "QCMS Technologies Pvt Ltd")))

        res = {
            "software_name": platform.software_name if platform else "QCMS Enterprise OS",
            "software_short_name": platform.software_short_name if platform else "QCMS",
            "software_display_name": platform.software_display_name if platform else "QCMS Enterprise Platform",
            "platform_title": platform.platform_title if platform else "QCMS Quality Management System",
            "platform_subtitle": platform.platform_subtitle if platform else "Enterprise Quality & Compliance Management System",
            "tagline": platform.tagline if platform else "Accelerating Enterprise Excellence & Compliance",
            "version": platform.version if platform else "v4.8.2-PROD",
            "edition": platform.edition if platform else "Enterprise Cloud Edition",
            "website": platform.website if platform else "https://qcms.io",
            "support_portal": platform.support_portal if platform else "https://support.qcms.io",
            "copyright_text": platform.copyright_text if platform else "© 2026 QCMS Enterprise Solutions. All rights reserved.",
            "footer_copyright": platform.footer_copyright if platform else "Confidential & Proprietary — Generated by QCMS Enterprise OS",
            
            # Company Info
            "legal_company_name": company.legal_company_name if company else "QCMS Technologies Pvt Ltd",
            "organization_name": org_name,
            "trading_name": company.trading_name if company else "QCMS Solutions",
            "gstin": company.gstin if company else "27AAACQ1234F1Z9",
            "pan": company.pan if company else "AAACQ1234F",
            "cin": company.cin if company else "U72200MH2026PTC123456",
            "iso_certifications": company.iso_certifications if company else "ISO 9001:2015 | ISO 27001:2022 | IATF 16949",
            "official_seal_url": company.official_seal_url if company else "/assets/img/official_seal.png",
            "digital_signature_url": company.digital_signature_url if company else "/assets/img/digital_signature.png",

            # Contacts
            "general_email": contacts.general_email if contacts else "info@qcms.com",
            "support_email": contacts.support_email if contacts else "support@qcms.com",
            "billing_email": contacts.billing_email if contacts else "billing@qcms.com",
            "sales_email": contacts.sales_email if contacts else "sales@qcms.com",
            "legal_email": contacts.legal_email if contacts else "legal@qcms.com",
            "general_phone": contacts.general_phone if contacts else "+1 (800) 555-0199",
            "support_phone": contacts.support_phone if contacts else "+1 (800) 555-0100",

            # Addresses
            "registered_office": addresses.registered_office if addresses else "Suite 800, Innovation Tower, BKC, Mumbai, MH 400051, India",
            "corporate_office": addresses.corporate_office if addresses else "Tech Park Phase 2, Whitefield, Bengaluru, KA 560066, India",

            # Assets
            "logo_url": assets.logo_url if assets else "/assets/img/logo.png",
            "print_logo_url": assets.print_logo_url if assets else "/assets/img/logo-print.png",
            "pdf_logo_url": assets.pdf_logo_url if assets else "/assets/img/logo-pdf.png",
            "watermark_logo_url": assets.watermark_logo_url if assets else "/assets/img/watermark.png"
        }
        cls._cache[cache_key] = res
        return res

    @classmethod
    def get_template_config(cls, template_key, org_id=None):
        """Fetch template-specific branding parameters (Invoice, QC Story, Certificates, Reports)."""
        cache_key = f"template:{template_key}:{org_id}"
        if cache_key in cls._cache:
            return cls._cache[cache_key]

        tmpl = DocumentTemplateConfig.query.filter_by(template_key=template_key, org_id=org_id).first()
        if not tmpl:
            tmpl = DocumentTemplateConfig.query.filter_by(template_key=template_key, org_id=None).first()
        
        ctx = cls.get_branding_context(org_id)
        
        if not tmpl:
            res = {
                "template_key": template_key,
                "header_title": ctx["platform_title"],
                "subtitle": ctx["platform_subtitle"],
                "header_text": ctx["software_display_name"],
                "footer_text": ctx["footer_copyright"],
                "watermark_text": "CONFIDENTIAL",
                "confidential_text": "STRICTLY CONFIDENTIAL — INTERNAL USE ONLY",
                "terms_and_conditions": "Payment due within 30 days. Standard SLA terms apply.",
                "disclaimer_text": "Generated electronically by certified QCMS Enterprise engine.",
                "enable_qr_verification": True,
                "enable_digital_signature": True
            }
        else:
            res = {
                "template_key": tmpl.template_key,
                "template_name": tmpl.template_name,
                "header_title": tmpl.header_title or ctx["platform_title"],
                "subtitle": tmpl.subtitle or ctx["platform_subtitle"],
                "header_text": tmpl.header_text or ctx["software_display_name"],
                "footer_text": tmpl.footer_text or ctx["footer_copyright"],
                "watermark_text": tmpl.watermark_text or "CONFIDENTIAL",
                "confidential_text": tmpl.confidential_text or "STRICTLY CONFIDENTIAL — INTERNAL USE ONLY",
                "terms_and_conditions": tmpl.terms_and_conditions or tmpl.footer_text or "Payment due within 30 days. Standard SLA terms apply.",
                "disclaimer_text": tmpl.disclaimer_text or "Generated electronically by certified QCMS Enterprise engine.",
                "enable_qr_verification": tmpl.enable_qr_verification,
                "enable_digital_signature": tmpl.enable_digital_signature,
                "settings_json": tmpl.settings_json or {}
            }

        cls._cache[cache_key] = res
        return res

    @staticmethod
    def generate_verification_metadata(doc_type, doc_id, user_name="System", org_id=None):
        """Generate verification QR code data, hash string, and document metadata."""
        ctx = DocumentBrandingService.get_branding_context(org_id)
        timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        raw_token = f"{doc_type}:{doc_id}:{timestamp}:{ctx['software_name']}"
        doc_hash = hashlib.sha256(raw_token.encode('utf-8')).hexdigest()[:16].upper()
        
        verification_url = f"{ctx['website']}/verify-doc?type={doc_type}&id={doc_id}&hash={doc_hash}"
        
        try:
            import qrcode, io, base64
            qr = qrcode.QRCode(version=1, box_size=4, border=1)
            qr.add_data(verification_url)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            buf = io.BytesIO()
            img.save(buf, format='PNG')
            b64_qr = base64.b64encode(buf.getvalue()).decode('utf-8')
            qr_image_url = f"data:image/png;base64,{b64_qr}"
        except Exception as e:
            qr_image_url = f"https://api.qrserver.com/v1/create-qr-code/?size=150x150&data={verification_url}"

        return {
            "document_hash": doc_hash,
            "verification_url": verification_url,
            "qr_image_url": qr_image_url,
            "generated_at": timestamp,
            "generated_by": user_name,
            "software": ctx["software_name"],
            "version": ctx["version"],
            "organization": ctx["organization_name"],
            "author": f"{user_name} via {ctx['software_name']}"
        }

    @staticmethod
    def wrap_email_html(body_html, title="QCMS Notification", org_id=None):
        """Wrap email content with centralized corporate email branding header/footer."""
        ctx = DocumentBrandingService.get_branding_context(org_id)
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body {{ font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f4f6f9; margin: 0; padding: 20px; color: #1e293b; }}
                .email-container {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }}
                .email-header {{ background: #1e293b; color: #ffffff; padding: 24px; text-align: center; border-bottom: 3px solid #2563eb; }}
                .email-header h1 {{ margin: 0; font-size: 20px; font-weight: 600; letter-spacing: 0.5px; }}
                .email-header p {{ margin: 4px 0 0 0; font-size: 12px; color: #94a3b8; }}
                .email-body {{ padding: 32px 24px; font-size: 15px; line-height: 1.6; color: #334155; }}
                .email-footer {{ background: #f8fafc; padding: 20px 24px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }}
                .email-footer a {{ color: #2563eb; text-decoration: none; }}
            </style>
        </head>
        <body>
            <div class="email-container">
                <div class="email-header">
                    <h1>{ctx['software_display_name']}</h1>
                    <p>{title}</p>
                </div>
                <div class="email-body">
                    {body_html}
                </div>
                <div class="email-footer">
                    <p style="margin:0 0 6px 0; font-weight:600;">{ctx['legal_company_name']} | {ctx['organization_name']}</p>
                    <p style="margin:0 0 6px 0;">{ctx['registered_office']}</p>
                    <p style="margin:0;">Support: <a href="mailto:{ctx['support_email']}">{ctx['support_email']}</a> | <a href="{ctx['website']}">{ctx['website']}</a></p>
                    <p style="margin:10px 0 0 0; font-size:11px; color:#94a3b8;">{ctx['copyright_text']}</p>
                </div>
            </div>
        </body>
        </html>
        """

