from datetime import datetime
from app.infrastructure.database.models.models import (
    db, PlatformIdentityConfig, CompanyInformationConfig, CompanyContactsConfig,
    CompanyAddressesConfig, BrandingAssetsConfig, DocumentTemplateConfig,
    SettingUsageMap, Organization
)

class SettingUsageScannerService:
    """Automatic Scanner & Impact Analysis Engine for Settings Usage Mapping."""

    @staticmethod
    def seed_initial_defaults():
        """Ensure default identity, company info, document templates and usage mappings exist."""
        # 1. Platform Identity
        if PlatformIdentityConfig.query.filter_by(org_id=None).first() is None:
            db.session.add(PlatformIdentityConfig(org_id=None))

        # 2. Company Info
        if CompanyInformationConfig.query.filter_by(org_id=None).first() is None:
            db.session.add(CompanyInformationConfig(org_id=None))

        # 3. Company Contacts
        if CompanyContactsConfig.query.filter_by(org_id=None).first() is None:
            db.session.add(CompanyContactsConfig(org_id=None))

        # 4. Company Addresses
        if CompanyAddressesConfig.query.filter_by(org_id=None).first() is None:
            db.session.add(CompanyAddressesConfig(org_id=None))

        # 5. Branding Assets
        if BrandingAssetsConfig.query.filter_by(org_id=None).first() is None:
            db.session.add(BrandingAssetsConfig(org_id=None))

        db.session.commit()

        # 6. Default Document Templates
        default_templates = [
            ("invoice", "Invoice & Billing Receipt Template", "TAX INVOICE", "Official Subscription Billing Receipt", "Terms: Payment due within 30 days. All taxes calculated as per local regulation."),
            ("qc_story", "QC Story Report Template", "QC STORY PROJECT REPORT", "Quality Control Project Problem Solving Report", "Confidential QC Story document. Unauthorized distribution prohibited."),
            ("certificate", "Training & SOP Certificate Template", "CERTIFICATE OF COMPLETION", "Official SOP Training & Assessment Certificate", "Certified digital credential issued under ISO 9001/27001 Quality Standards."),
            ("analytics", "Analytics & Executive Report Template", "EXECUTIVE ANALYTICS REPORT", "Platform Usage & Financial Performance Summary", "Strictly Confidential — Executive Leadership Dashboard Summary."),
            ("audit", "Audit & Compliance Report Template", "COMPLIANCE AUDIT REPORT", "ISO & Regulatory Compliance Verification Summary", "Official Quality Audit Document. Validated under ISO 9001:2015 Standards."),
            ("project", "Project Summary Report Template", "PROJECT STATUS SUMMARY", "Detailed Project Milestone & Task Ledger", "Internal project management milestone report."),
            ("export", "Excel / CSV Data Export Template", "DATA EXPORT LEDGER", "Raw Data Export & Analytical Extract", "Automated system ledger extract.")
        ]

        for key, name, title, sub, terms in default_templates:
            if not DocumentTemplateConfig.query.filter_by(template_key=key, org_id=None).first():
                db.session.add(DocumentTemplateConfig(
                    org_id=None,
                    template_key=key,
                    template_name=name,
                    header_title=title,
                    subtitle=sub,
                    header_text=f"QCMS Enterprise — {title}",
                    footer_text="Confidential & Proprietary — Generated by QCMS Enterprise OS Engine",
                    terms_and_conditions=terms,
                    enable_qr_verification=True,
                    enable_digital_signature=True
                ))

        db.session.commit()

        # 7. Seed Usage Mappings
        SettingUsageScannerService.scan_and_sync_dependencies()

    @staticmethod
    def scan_and_sync_dependencies():
        """Scans codebase definitions and populates setting_usage_map database table."""
        mappings = [
            # Software Name / Platform Identity
            ("software_name", "Software Name", "Platform Identity", "Branding Header", "Header Bar & Navigation", "/admin/super-admin.html", "/api/system/settings", "BrandingService", "Web App", "Header Template", "Web", "frontend/admin/super-admin.html"),
            ("software_name", "Software Name", "Billing & Subscriptions", "Invoice PDF", "Tax Invoice Header", "/admin/settings.html", "/api/billing/invoice/download", "InvoiceGenerator", "Invoice", "Invoice Template", "PDF", "backend/app/presentation/routes/billing_routes.py"),
            ("software_name", "Software Name", "QC Story Module", "QC Story PDF", "QC Story Header", "/admin/qc-story.html", "/api/reports/qc-story/export", "QCStoryGenerator", "QC Story Report", "QC Story Template", "PDF", "backend/app/presentation/routes/reports_routes.py"),
            ("software_name", "Software Name", "Training & SOPs", "Training Certificate", "Certificate Header", "/admin/training.html", "/api/training/certificate", "CertificateGenerator", "Certificate", "Certificate Template", "PDF", "backend/app/presentation/routes/training_routes.py"),
            ("software_name", "Software Name", "Notifications & Email", "Email Service", "Welcome Email Header", "N/A", "/api/users/invite", "EmailService", "Email", "Welcome Email Template", "Email", "backend/app/infrastructure/mailer/email_service.py"),
            ("software_name", "Software Name", "Analytics & Reports", "Excel Exporters", "Excel Metadata Author", "/admin/super-admin.html?view=analytics", "/api/reports/analytics/export", "ReportExporter", "Analytics Report", "Excel Template", "Excel", "backend/app/presentation/routes/reports_routes.py"),

            # Company Legal Name
            ("legal_company_name", "Legal Company Name", "Company Info", "Invoice PDF", "Billed From / Issued By", "/admin/settings.html", "/api/billing/invoice/download", "InvoiceGenerator", "Invoice", "Invoice Template", "PDF", "backend/app/presentation/routes/billing_routes.py"),
            ("legal_company_name", "Legal Company Name", "Training & SOPs", "Training Certificate", "Issuing Authority", "/admin/training.html", "/api/training/certificate", "CertificateGenerator", "Certificate", "Certificate Template", "PDF", "backend/app/presentation/routes/training_routes.py"),
            ("legal_company_name", "Legal Company Name", "Notifications & Email", "Email Footers", "Legal Disclaimer Footer", "N/A", "/api/users/invite", "EmailService", "Email", "Email Footer Template", "Email", "backend/app/infrastructure/mailer/email_service.py"),
            ("legal_company_name", "Legal Company Name", "Compliance & Audit", "Compliance Reports", "ISO Regulatory Disclaimer", "/admin/super-admin.html?view=compliance", "/api/reports/compliance", "ComplianceService", "Compliance Report", "Audit Template", "PDF", "backend/app/presentation/routes/reports_routes.py"),

            # Support Email
            ("support_email", "Support Email", "Contact Directory", "Support Center", "Help & Contact Page", "/admin/settings.html", "/api/system/settings", "SupportService", "Web Page", "Contact Section", "Web", "frontend/admin/settings.html"),
            ("support_email", "Support Email", "Billing & Invoices", "Invoice Footer", "Payment Support Note", "/admin/settings.html", "/api/billing/invoice/download", "InvoiceGenerator", "Invoice", "Invoice Template", "PDF", "backend/app/presentation/routes/billing_routes.py"),
            ("support_email", "Support Email", "Notifications & Email", "Password Reset Email", "Support Reply-To", "N/A", "/api/auth/reset-password", "EmailService", "Email", "Reset Password Template", "Email", "backend/app/infrastructure/mailer/email_service.py"),

            # GSTIN
            ("gstin", "GSTIN", "Tax & Legal Settings", "Tax Invoices", "GST Tax Breakdown Header", "/admin/settings.html", "/api/billing/invoice/download", "InvoiceGenerator", "Invoice", "Invoice Template", "PDF", "backend/app/presentation/routes/billing_routes.py"),
            ("gstin", "GSTIN", "Audit Logs", "Financial Audit", "Tax Compliance Ledger", "/admin/super-admin.html?view=audit", "/api/reports/tax-audit", "AuditService", "Audit Log", "Tax Audit Template", "Excel", "backend/app/presentation/routes/reports_routes.py"),

            # Company Logo
            ("logo_url", "Company Logo", "Branding Assets", "Login Screen", "Brand Banner Logo", "/login.html", "N/A", "StaticAsset", "Web Page", "Login Form", "Web", "frontend/login.html"),
            ("logo_url", "Company Logo", "Navigation", "Top Navbar Logo", "Sidebar Brand Badge", "/admin/super-admin.html", "/api/system/settings", "BrandingService", "Web Header", "Main Navigation", "Web", "frontend/admin/super-admin.html"),
            ("logo_url", "Company Logo", "PDF Reports", "Report Header Logo", "PDF Canvas Banner", "All Pages", "/api/reports/*", "DocumentBrandingService", "PDF Document", "Header Component", "PDF", "backend/app/domain/services/document_branding_service.py"),

            # Watermark Text
            ("watermark_text", "Watermark Text", "Document Branding", "PDF Engine", "Canvas Background Watermark", "All PDF Downloads", "/api/reports/*", "DocumentBrandingService", "PDF Document", "Watermark Layer", "PDF", "backend/app/domain/services/document_branding_service.py"),
            ("watermark_text", "Watermark Text", "Print Pages", "Browser Print", "Print Overlay Badge", "All Printable Views", "N/A", "PrintEngine", "Print Page", "CSS Print Template", "Print", "frontend/assets/js/print-engine.js")
        ]

        for key, name, mod, feat, comp, page, route, svc, doc_type, tmpl, exp_type, file_path in mappings:
            existing = SettingUsageMap.query.filter_by(setting_key=key, component=comp, file_path=file_path).first()
            if not existing:
                db.session.add(SettingUsageMap(
                    setting_key=key,
                    setting_name=name,
                    module=mod,
                    feature=feat,
                    component=comp,
                    page=page,
                    route=route,
                    backend_service=svc,
                    document_type=doc_type,
                    template=tmpl,
                    export_type=exp_type,
                    file_path=file_path,
                    dependency_type="Direct",
                    usage_category="Branding"
                ))

        db.session.commit()

    @staticmethod
    def get_impact_analysis(setting_key):
        """Calculates total affected components, modules, exports, and pages for a given setting key."""
        records = SettingUsageMap.query.filter_by(setting_key=setting_key).all()
        if not records:
            # Fallback fuzzy match for all setting keys
            records = SettingUsageMap.query.all()

        modules = set()
        export_types = set()
        components = set()

        for r in records:
            if r.setting_key == setting_key or not setting_key:
                modules.add(r.module)
                export_types.add(r.export_type)
                components.add(r.component)

        return {
            "setting_key": setting_key,
            "total_dependencies": len(records),
            "affected_modules_count": len(modules),
            "affected_modules": list(modules),
            "affected_export_types": list(export_types),
            "affected_components_count": len(components),
            "dependencies": [r.to_dict() for r in records]
        }

    @staticmethod
    def get_dependency_graph():
        """Generates interactive hierarchical dependency graph structure."""
        all_records = SettingUsageMap.query.all()
        nodes = []
        edges = []

        # Root node
        nodes.append({"id": "root", "label": "Document Identity & Settings Matrix", "type": "root"})

        # Group by setting_key
        keys_set = set(r.setting_key for r in all_records)
        for k in keys_set:
            nodes.append({"id": f"key_{k}", "label": k.replace('_', ' ').title(), "type": "setting"})
            edges.append({"from": "root", "to": f"key_{k}"})

        # Group by module / export_type
        for r in all_records:
            comp_id = f"comp_{r.id}"
            nodes.append({"id": comp_id, "label": f"{r.component} ({r.export_type})", "type": "component"})
            edges.append({"from": f"key_{r.setting_key}", "to": comp_id})

        return {"nodes": nodes, "edges": edges}
